### ISSUE TITLE
Build path to assets

### ISSUE THREAD

**Issue by RobLeachman** [iwantantra/vite-phaser-ts#1]
Maybe it's just me, `npm run build` looks good... except it builds for the website root

http://myserver.foo/path/to/index.html -- works fine
http://myserver.foo/vite.svg -- 404, this is the generated URL
http://myserver.foo/path/to/vite.svg -- this is the actual URL

`npm run dev` is groovy and testing `npm run build` locally with node's `http-server` works because we start that server from `cd /src/vite-phaser-ts/dist`

I hope this is clear and correctable. When I find the fix I'll come back and add it.

Thanks!

**Comment by RobLeachman** [comment]
Hey hey I think this fixes it! Added `vite.config.ts`

```
/** @type {import('vite').UserConfig} */
import { defineConfig } from 'vite'
export default defineConfig({
  base: './'
});
```

**Comment by iwantantra** [comment]
Hi , thank you
I added `vite.config.js` file
